title: Allen Smith Creative
description: I'm a dad who tells stories with code, movies, and music.
meta_description: "I'm a dad who tells stories with code, movies, and music."

markdown: kramdown
highlighter: rouge

baseurl: /
domain_name: 'https://loranallensmith.com'
url:            'https://loranallensmith.com'

author: loranallensmith

# SEO Info
google_site_verification: 'UA-78818462-2'

twitter:
  username: loranallensmith
  card: summary

logo: /images/allensmith-profile.png

social:
  - https://twitter.com/loranallensmith
  - https://linkedin.com/in/loranallensmith
  - https://github.com/loranallensmith

linkedin: loranallensmith
github: loranallensmith
email: allen@loranallensmith.com

permalink:       /:year/:title/

sass:
  sass_dir: assets/sass

collections:
  showpieces:
    output: false

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /images/allensmith-profile.jpg
