title: Allen Smith
description: I'm a dad who tells stories with code, movies, and music.
meta_description: "I'm a dad who tells stories with code, movies, and music."

markdown: kramdown
highlighter: rouge

baseurl: /
domain_name: 'https://loranallensmith.me'
url:            'https://loranallensmith.me'

author: loranallensmith

# SEO Info
google_site_verification: 'UA-54264286-1'

twitter:
  username: loranallensmith
  card: summary_large_image

logo: /images/allensmith-profile.png

social:
  - https://twitter.com/loranallensmith
  - https://linkedin.com/in/loranallensmith
  - https://github.com/loranallensmith

linkedin: loranallensmith
github: loranallensmith
email: info@loranallensmith.me

permalink:       /:year/:title/

collections:
  showpieces:
    output: false

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /images/allensmith-profile.jpg
